###################################################
# General purpose Makefile for LaTeX-Documents    #
#                                                 #
# Based on the makefile written by Daniel Ciaglia #
# http://www.sigterm.de/misc/src/Makefile-latex   #
#                                                 #
# Modified by Finn                                #
# Modified by Daniel                              #
###################################################

##### Variables #############
#############################

# empty vars for dependencies
PICS=

# dependencies of the Document
define build_latex
-include $(1).d 

clean-latex: clean-latex-$(1)
clean-latex-$(1): $(GEN_IMAGES)
	@rm -f $(1).{${LATEX_EXTENSION}}
endef


# ATTENTION!
# File-extensions to delete on clean and clean-latex
LATEX_EXTENSION := aux,toc,log,lof,lot,lol,bbl,blg,out,ind,ilg,idx,lof,lot,loAL,d
# file with list of generated images to clean up
ifndef GEN_IMAGES
GEN_IMAGES := .generated_images
endif


#############################
#############################

PDFLATEX := $(shell which pdflatex)
PDFLATEX_CMD = $(PDFLATEX) \
	-output-directory=$(dir $*) \
	-file-line-error \
	-halt-on-error   \
	-interaction=batchmode \

RERUN := Rerun to get cross-references right\|There were undefined references
DEP_TEX:=  $(dir $(lastword $(MAKEFILE_LIST)))/depends_tex.awk

# TEX dependencies $(DEP_TEX)
%.d : %.tex
	@ awk -f $(DEP_TEX) $*.tex > $*.d

# PDF
%.pdf: %.tex  $(STYLES) $(LATEX_INDEXFILE)
	@ awk -f $(DEP_TEX) $*.tex > $*.d &
ifndef PDFLATEX
	$(error you need to have pdflatex installed and in your path)
endif
	@ $(PDFLATEX_CMD) $* >/dev/null || { cat $*.log; false; }
	-@ bibtex $*
	@ if  grep -e '$(RERUN)' $*.log; then \
	    echo "LaTeX rerun $@"; \
	    $(PDFLATEX_CMD) $* >/dev/null || { cat $*.log; false; } \
	  fi
ifdef LATEX_INDEXFILE
	-@ makeindex -c -g -s $ $*
	 @ if grep -e '$(RERUN)' $*.log; then \
	    echo "LaTeX rerun $@"; \
	    $(PDFLATEX_CMD) $* >/dev/null || { cat $*.log; false; } \
	  fi
endif
	@latex_count=3 ; \
	  while \
	  	   grep -e '$(RERUN)' $*.log \
		&& [ $$latex_count -gt 0 ] ;\
	    do \
	    	echo "LaTeX rerun $@"; \
	      $(PDFLATEX_CMD) $* >/dev/null || { cat $*.log; false; }; \
	      latex_count=`expr $$latex_count - 1` ; \
	    done || true;
	@echo -e "\nDone, based on: $^\n"
	@grep -e "Warning:\|Error:" $*.log || echo "No warnings."



# Clean
clean: clean-latex
clean-latex: $(GEN_IMAGES)
	@rm -fv `cat $(GEN_IMAGES)`
	@rm -fv $(GEN_IMAGES)

.PHONY: all clean ps pdf everything report
.SUFFIXES: .dvi .ps .pdf .tex .d
.SECONDARY: $(PICS:.pic=.eps) $(PICS:.pic=.pdf) $(PICS:.pic=.svg)


QE:=2>/dev/null

DIA      := $(shell which dia      $(QE))
INKSCAPE := $(shell which inkscape $(QE))
CONVERT  := $(shell which convert  $(QE))
FIG2DEV  := $(shell which fig2dev  $(QE))
GNUPLOT  := $(shell which gnuplot  $(QE))
EPS2PDF  := $(shell which epstopdf $(QE) || which a2ping   $(QE)  )

%.pic: %.pdf
	@ echo $@ >> $(GEN_IMAGES)
	@ touch $@	

%.eps: %.plot %.dat
ifndef GNUPLOT
	$(error "You need gnuplot installed and in your path!")
endif
	@ echo $@ >> $(GEN_IMAGES)
	cd $(dir $<) && $(GNUPLOT) $(notdir $<)

%.pdf: %.fig
ifndef FIG2DEV
	$(error "You need fig2dev installed in your path")
endif
	@ echo $@ >> $(GEN_IMAGES)
	$(FIG2DEV) -L pdf $< $@

ifdef INKSCAPE
%.pdf: %.svg 
	@ echo $@ >> $(GEN_IMAGES)
	$(INKSCAPE) -z -A -E $@ $< 
%.eps: %.svg 
	@ echo $@ >> $(GEN_IMAGES)
	$(INKSCAPE) -z -T -E $@ $< 
%.svg: %.dia 
ifndef DIA
	$(error "You need dia installed and in your path!")
endif
	@ echo $@ >> $(GEN_IMAGES)
	$(DIA) -e $@ -t svg $<
else
%.eps: %.dia
ifndef DIA
	$(error "You need dia installed and in your path!")
endif
	@ echo $@ >> $(GEN_IMAGES)
	$(DIA) -e $@ -t eps $<

%.eps: %.svg
ifndef CONVERT
	$(error "You need convert (ImageMagick) installed and in your path!")
endif
	@ echo $@ >> $(GEN_IMAGES)
	$(CONVERT) $< $@
endif

%.pdf: %.eps 
ifndef EPS2PDF
	$(error "You need a2ping or epstopdf installed and in your path!")
endif
	@ echo $@ >> $(GEN_IMAGES)
	$(EPS2PDF) $< 

$(GEN_IMAGES):
	@mkdir -p $(dir $@)
	@touch $@

# vim: ft=make
